####################################################
## ATD Tenant Specific Information - VRFs / VLANs ##
####################################################

# Tenant BLUE Specific Information - VRFs / VLANs

ATD_BLUE:
  enable_mlag_ibgp_peering_vrfs: false
  mac_vrf_vni_base: 10000
  vrfs:
    BLUE:
      vrf_vni: 502
      vtep_diagnostic:
        loopback: 102
        #Loopback pool 10.0.10.0/24
        loopback_ip_pools:
          - pod: SITE1_POD
            ipv4_pool: 10.0.10.64/27
          - pod: SITE2_POD
            ipv4_pool: 10.0.10.96/27

      svis:
        202:
          name: BLUE_VLAN_202
          tags: [ SITE1_DC, SITE2_DC ]
          enabled: true
          ip_address_virtual: 10.100.202.1/24
