####################################################
## ATD Tenant Specific Information - VRFs / VLANs ##
####################################################

# Tenant RED Specific Information - VRFs / VLANs

ATD_RED:
  enable_mlag_ibgp_peering_vrfs: false
  mac_vrf_vni_base: 10000
  vrfs:
    RED:
      vrf_vni: 501
      vtep_diagnostic:
        loopback: 101
        #Loopback pool 10.0.10.0/24
        loopback_ip_pools:
          - pod: SITE1_POD
            ipv4_pool: 10.0.10.0/27
          - pod: SITE2_POD
            ipv4_pool: 10.0.10.32/27

      svis:
        101:
          name: RED_VLAN_101
          tags: [ SITE1_DC, SITE2_DC ]
          enabled: true
          ip_address_virtual: 10.100.1.1/24
