####################################################
## ATD Tenant Specific Information - VRFs / VLANs ##
####################################################

# Tenant BLUE Specific Information - VRFs / VLANs

ATD_BLUE:
  enable_mlag_ibgp_peering_vrfs: false
  mac_vrf_vni_base: 10000
  vrfs:
    BLUE:
      vrf_vni: 501
      vtep_diagnostic:
        loopback: 101
        loopback_ip_pools:
          - pod: SITE1_POD
            ipv4_pool: 10.0.10.64/27
          - pod: SITE2_POD
            ipv4_pool: 10.0.10.96/27

      svis:
        101:
          name: BLUE_VLAN_101
          tags: [ SITE1_DC, SITE2_DC ]
          enabled: true
          ip_address_virtual: 10.100.1.1/24
        801:
          name: BGP_FOR_VRF_BLUE_CORE1
          tags: [SITE1_BRDR, SITE2_BRDR]
          enabled: true
          nodes:
            s1-brdr1:
              ip_address: 10.3.1.3/29
            s1-brdr2:
              ip_address: 10.3.1.4/29
            s2-brdr1:
              ip_address: 10.3.1.5/29
            s2-brdr2:
              ip_address: 10.3.1.6/29
        811:
          name: BGP_FOR_VRF_BLUE_CORE2
          tags: [SITE1_BRDR, SITE2_BRDR]
          enabled: true
          nodes:
            s1-brdr1:
              ip_address: 10.4.1.3/29
            s1-brdr2:
              ip_address: 10.4.1.4/29
            s2-brdr1:
              ip_address: 10.4.1.5/29
            s2-brdr2:
              ip_address: 10.4.1.6/29
      bgp_peers:
        10.3.1.2:
          remote_as: 65121
          peer_group: S1-CORE1-PEERS
          description: S1-CORE1-PEERS
          nodes: [ s1-brdr1, s1-brdr2 ]
        10.3.1.1:
          remote_as: 65221
          peer_group: S2-CORE1-PEERS
          description: S2-CORE1-PEERS
          nodes: [ s2-brdr1, s2-brdr2 ]
        10.4.1.2:
          remote_as: 65121
          peer_group: S1-CORE2-PEERS
          description: S1-CORE2-PEERS
          nodes: [ s1-brdr1, s1-brdr2 ]
        10.4.1.1:
          remote_as: 65221
          peer_group: S2-CORE2-PEERS
          description: S2-CORE2-PEERS
          nodes: [ s2-brdr1, s2-brdr2 ]
