####################################################
## ATD Tenant Specific Information - VRFs / VLANs ##
####################################################

# Tenant RED Specific Information - VRFs / VLANs

ATD_RED:
  enable_mlag_ibgp_peering_vrfs: false
  mac_vrf_vni_base: 10000
  vrfs:
    RED:
      vrf_vni: 503
      vtep_diagnostic:
        loopback: 103
        loopback_ip_pools:
          - pod: SITE1_POD
            ipv4_pool: 10.0.10.0/27
          - pod: SITE2_POD
            ipv4_pool: 10.0.10.32/27

      svis:
        303:
          name: RED_VLAN_303
          tags: [ SITE1_DC, SITE2_DC ]
          enabled: true
          ip_address_virtual: 10.100.3.1/24
        803:
          name: BGP_FOR_VRF_RED_CORE1
          tags: [SITE1_BRDR, SITE2_BRDR]
          enabled: true
          nodes:
            s1-brdr1:
              ip_address: 10.3.3.3/29
            s1-brdr2:
              ip_address: 10.3.3.4/29
            s2-brdr1:
              ip_address: 10.3.3.5/29
            s2-brdr2:
              ip_address: 10.3.3.6/29
        813:
          name: BGP_FOR_VRF_RED_CORE2
          tags: [SITE1_BRDR, SITE2_BRDR]
          enabled: true
          nodes:
            s1-brdr1:
              ip_address: 10.4.3.3/29
            s1-brdr2:
              ip_address: 10.4.3.4/29
            s2-brdr1:
              ip_address: 10.4.3.5/29
            s2-brdr2:
              ip_address: 10.4.3.6/29
      bgp_peers:
        10.3.3.2:
          remote_as: 65121
          peer_group: S1-CORE1-PEERS
          description: S1-CORE1-PEERS
          nodes: [ s1-brdr1, s1-brdr2 ]
        10.3.3.1:
          remote_as: 65221
          peer_group: S2-CORE1-PEERS
          description: S2-CORE1-PEERS
          nodes: [ s2-brdr1, s2-brdr2 ]
        10.4.3.2:
          remote_as: 65121
          peer_group: S1-CORE2-PEERS
          description: S1-CORE2-PEERS
          nodes: [ s1-brdr1, s1-brdr2 ]
        10.4.3.1:
          remote_as: 65221
          peer_group: S2-CORE2-PEERS
          description: S2-CORE2-PEERS
          nodes: [ s2-brdr1, s2-brdr2 ]
