- include_vars:
    file: ~/project/labfiles/AristaValidatedDesigns/ATD-AVD-Dual-DC/intended/structured_configs/cvp/ATD_CVP.yml

- name: "Gather CVP facts {{inventory_hostname}}"
  arista.cvp.cv_facts_v3:
    facts:
      - devices
  register: CVP_FACTS

- name: "Removing ATD-INFRA from Tenant container"
  arista.cvp.cv_device_v3:
    devices: '{{CVP_DEVICES}}'
    state: present
    apply_mode: strict
  when: CVP_FACTS.data.cvp_devices | map(attribute='configlets') | regex_findall('BaseIPv4_') | length  == 0


# - debug:
#     msg: '{{CVP_FACTS.data.cvp_devices | map(attribute="configlets") | regex_findall("AVD") | length }}'