- include_vars:
    file: "{{lookup('env','PWD')}}/intended/structured_configs/cvp/ATD_CVP.yml"

- name: "Gather CVP facts {{inventory_hostname}}"
  arista.cvp.cv_facts_v3:
    facts:
      - devices
  register: CVP_FACTS

- name: "Removing legacy configlets from devices"
  arista.cvp.cv_device_v3:
    devices: '{{CVP_DEVICES}}'
    state: present
    apply_mode: strict
  when: CVP_FACTS.data.cvp_devices | map(attribute='configlets') | regex_findall('BASE_') | length  > 0
  register: CVP_RESULTS

- name: "Execute pending tasks on {{inventory_hostname}}"
  arista.cvp.cv_task_v3:
    tasks: "{{ CVP_RESULTS.taskIds }}"
