---

- name: "Building initial Containers topology"
  tags: [provision, apply]
  arista.cvp.cv_container_v3:
    topology: '{{CVP_CONTAINERS_INIT}}'

- name: "Moving devices to Staging container"
  tags: [provision, apply]
  arista.cvp.cv_device_v3:
    devices: "{{CVP_DEVICES_INIT}}"
    state: present
    #apply_mode: strict
  register: CVP_DEVICES_RESULTS

- name: "Execute pending tasks on {{inventory_hostname}}"
  tags: [apply]
  arista.cvp.cv_task_v3:
    tasks: "{{ CVP_DEVICES_RESULTS.taskIds }}"
  when:
    - CVP_DEVICES_RESULTS.taskIds | length > 0


- name: "Refresh Containers topology on {{inventory_hostname}}"
  tags: [provision, apply]
  arista.cvp.cv_container_v3:
    topology: '{{CVP_CONTAINERS_DELETE}}'
    state: absent

- name: "Cleaning up Tenant Container Configlet"
  command: "python3 service_scripts/configlet_remove.py"
  register: result
  ignore_errors: true

- name: "Initial ATD Setup Complete"
  debug:
    msg: "Setup is complete execute make fabric-provisioning next"

