---

# ----------------------  ATD L3 Leaf Layer (Core Switches) ---------------------- #

type: l3leaf

pod_name: SITE1_POD

l3leaf:
  defaults:
    platform: ceos
    uplink_ipv4_pool: 10.1.7.0/24
    loopback_ipv4_pool: 10.1.8.0/24
    vtep_loopback_ipv4_pool: 10.1.9.0/24
    mlag_peer_l3_ipv4_pool: 10.1.10.0/24
    mlag_peer_ipv4_pool: 10.1.11.0/24
    uplink_switches: ['s1-brdr1', 's1-brdr2']
    uplink_switch_interfaces: "{{ CEOS_CORE_UPLINK_Interfaces }}"
    max_uplink_switches: 2
    #evpn_route_servers: "{{ atd_evpn_route_servers }}"
    spanning_tree_mode: mstp
    #spanning_tree_priority: 45056
    virtual_router_mac_address : "{{ atd_virtual_router_mac_address }}"
    bgp_defaults: "{{ atd_bgp_defaults }}"
    mlag_interfaces: "{{ CEOS_MLAG_Interfaces }}"
  node_groups:
    SITE1_CORE_LEAF1:
      bgp_as: 65121
      filter:
        tenants: [all]
        tags: [SITE1_CORE]
      nodes:
        s1-core1:
          id: 1
          mgmt_ip: 192.168.0.102/24
        s1-core2:
          id: 2
          mgmt_ip: 192.168.0.103/24
