---

# ----------------------  ATD L3 Leaf Layer (DC, Border, Campus, ATD Hosts) ---------------------- #

type: l3leaf

pod_name: SITE1_POD

l3leaf:
  defaults:
    platform: ceos
    uplink_ipv4_pool: 10.1.2.0/24
    loopback_ipv4_pool: 10.1.3.0/24
    vtep_loopback_ipv4_pool: 10.1.4.0/24
    mlag_peer_l3_ipv4_pool: 10.1.5.0/24
    mlag_peer_ipv4_pool: 10.1.6.0/24
    uplink_switches: ['s1-spine1', 's1-spine2']
    uplink_interfaces: "{{ CEOS_SPINE_UPLINK_Interfaces }}"
    max_uplink_switches: 4
    #evpn_route_servers: "{{ atd_evpn_route_servers }}"
    spanning_tree_mode: mstp
    #spanning_tree_priority: 45056
    virtual_router_mac_address : "{{ atd_virtual_router_mac_address }}"
    bgp_defaults: "{{ atd_bgp_defaults }}"
    mlag_interfaces: "{{ CEOS_MLAG_Interfaces }}"
  node_groups:
    SITE1_DC_LEAF1:
      bgp_as: 65111
      filter:
        tenants: [all]
        tags: [SITE1_DC]
      nodes:
        s1-leaf1:
          id: 1
          mgmt_ip: 192.168.0.12/24
          uplink_switch_interfaces: ['Ethernet2', 'Ethernet2']
        s1-leaf2:
          id: 2
          mgmt_ip: 192.168.0.13/24
          uplink_switch_interfaces: ['Ethernet3', 'Ethernet3']
    SITE1_DC_LEAF2:
      bgp_as: 65112
      filter:
        tenants: [all]
        tags: [SITE1_DC]
      nodes:
        s1-leaf3:
          id: 3
          mgmt_ip: 192.168.0.14/24
          uplink_switch_interfaces: ['Ethernet4', 'Ethernet4']
        s1-leaf4:
          id: 4
          mgmt_ip: 192.168.0.15/24
          uplink_switch_interfaces: ['Ethernet5', 'Ethernet5']
    SITE1_BORDER_LEAF1:
      bgp_as: 65113
      filter:
        tenants: [all]
        tags: [SITE1_DC, SITE1_BRDR]
      nodes:
        s1-brdr1:
          id: 5
          mgmt_ip: 192.168.0.100/24
          uplink_switch_interfaces: ['Ethernet7', 'Ethernet7']
        s1-brdr2:
          id: 6
          mgmt_ip: 192.168.0.101/24
          uplink_switch_interfaces: ['Ethernet8', 'Ethernet8']
