---

# ----------------------  ATD L3 Leaf Layer (Core Switches) ---------------------- #

type: l2leaf

pod_name: SITE2_POD

l2leaf:
  defaults:
    platform: ceos
    evpn_role: none
    # uplink_ipv4_pool: 10.2.7.0/24
    # loopback_ipv4_pool: 10.2.8.0/24
    # vtep_loopback_ipv4_pool: 10.2.9.0/24
    # mlag_peer_l3_ipv4_pool: 10.2.10.0/24
    mlag_peer_ipv4_pool: 10.2.11.0/24
    uplink_switches: ['s2-brdr1', 's2-brdr2']
    uplink_interfaces: "{{ CEOS_CORE_UPLINK_Interfaces }}"
    max_uplink_switches: 2
    #evpn_route_servers: "{{ atd_evpn_route_servers }}"
    spanning_tree_mode: mstp
    #spanning_tree_priority: 45056
    virtual_router_mac_address : "{{ atd_virtual_router_mac_address }}"
    #bgp_defaults: "{{ atd_bgp_defaults }}"
    mlag_interfaces: "{{ CEOS_MLAG_Interfaces }}"
  node_groups:
    SITE2_CORE_LEAF1:
      #bgp_as: 65221
      filter:
        tenants: [all]
        tags: [SITE2_CORE]
      nodes:
        s2-core1:
          id: 1
          mgmt_ip: 192.168.0.202/24
          uplink_switch_interfaces: ['Ethernet4', 'Ethernet4']
        s2-core2:
          id: 2
          mgmt_ip: 192.168.0.203/24
          uplink_switch_interfaces: ['Ethernet5', 'Ethernet5']
