---

CVP_DEVICES_INIT:
  - fqdn: s1-leaf1
    parentContainerName: STAGING
    configlets:
      - BaseIPv4_S1-Leaf1
  - fqdn: s1-leaf2
    parentContainerName: STAGING
    configlets:
      - BaseIPv4_S1-Leaf2
  - fqdn: s1-leaf3
    parentContainerName: STAGING
    configlets:
      - BaseIPv4_S1-Leaf3
  - fqdn: s1-leaf4
    parentContainerName: STAGING
    configlets:
      - BaseIPv4_S1-Leaf4
  - fqdn: s1-brdr1
    parentContainerName: STAGING
    configlets:
      - BaseIPv4_S1-Brdr1
  - fqdn: s1-brdr2
    parentContainerName: STAGING
    configlets:
      - BaseIPv4_S1-Brdr2
  - fqdn: s1-core1
    parentContainerName: STAGING
    configlets:
      - BaseIPv4_S1-Core1
  - fqdn: s1-core2
    parentContainerName: STAGING
    configlets:
      - BaseIPv4_S1-Core2
  - fqdn: s1-spine1
    parentContainerName: STAGING
    configlets:
      - BaseIPv4_S1-Spine1
  - fqdn: s1-spine2
    parentContainerName: STAGING
    configlets:
       - BaseIPv4_S1-Spine2
  - fqdn: s1-host1
    parentContainerName: STAGING
    configlets:
       - BaseIPv4_S1-Host1
  - fqdn: s1-host2
    parentContainerName: STAGING
    configlets:
       - BaseIPv4_S1-Host2
  - fqdn: s2-leaf1
    parentContainerName: STAGING
    configlets:
      - BaseIPv4_S2-Leaf1
  - fqdn: s2-leaf2
    parentContainerName: STAGING
    configlets:
      - BaseIPv4_S2-Leaf2
  - fqdn: s2-leaf3
    parentContainerName: STAGING
    configlets:
      - BaseIPv4_S2-Leaf3
  - fqdn: s2-leaf4
    parentContainerName: STAGING
    configlets:
      - BaseIPv4_S2-Leaf4
  - fqdn: s2-brdr1
    parentContainerName: STAGING
    configlets:
      - BaseIPv4_S2-Brdr1
  - fqdn: s2-brdr2
    parentContainerName: STAGING
    configlets:
      - BaseIPv4_S2-Brdr2
  - fqdn: s2-core1
    parentContainerName: STAGING
    configlets:
      - BaseIPv4_S2-Core1
  - fqdn: s2-core2
    parentContainerName: STAGING
    configlets:
      - BaseIPv4_S2-Core2
  - fqdn: s2-spine1
    parentContainerName: STAGING
    configlets:
      - BaseIPv4_S2-Spine1
  - fqdn: s2-spine2
    parentContainerName: STAGING
    configlets:
      - BaseIPv4_S2-Spine2
  - fqdn: s2-host1
    parentContainerName: STAGING
    configlets:
      - BaseIPv4_S2-Host1
  - fqdn: s2-host2
    parentContainerName: STAGING
    configlets:
      - BaseIPv4_S2-Host2

CVP_CONTAINERS_INIT:
  STAGING:
    parentContainerName: Tenant
    configlets:
      - ATD-INFRA

CVP_CONTAINERS_DELETE:
  S1-Leaf:
    parentContainerName: S1
  S1-Brdr:
    parentContainerName: S1
  S1-Core:
    parentContainerName: S1
  S1-Spine:
    parentContainerName: S1
  S1-Hosts:
    parentContainerName: S1
  S1:
    parentContainerName: Tenant
  S2-Leaf:
    parentContainerName: S2
  S2-Brdr:
    parentContainerName: S2
  S2-Core:
    parentContainerName: S2
  S2-Spine:
    parentContainerName: S2
  S2-Hosts:
    parentContainerName: S2
  S2:
    parentContainerName: Tenant
  Hosts:
    parentContainerName: Tenant