---
custom_structured_configuration_host_vlan_interfaces:
  Vlan701:
    description: iBGP_FOR_VRF_BLUE
    ip_address: 10.1.17.2/30
    vrf: BLUE
    shutdown: false
  Vlan702:
    description: iBGP_FOR_VRF_GREEN
    ip_address: 10.1.18.2/30
    vrf: GREEN
    shutdown: false
  Vlan703:
    description: iBGP_FOR_VRF_RED
    ip_address: 10.1.19.2/30
    vrf: RED
    shutdown: false
  Vlan801:
    description: BGP_FOR_VRF_BLUE
    ip_address: 10.3.1.2/29
    vrf: BLUE
    shutdown: false
  Vlan802:
    description: BGP_FOR_VRF_GREEN
    ip_address: 10.3.2.2/29
    vrf: GREEN
    shutdown: false
  Vlan803:
    description: BGP_FOR_VRF_RED
    ip_address: 10.3.3.2/29
    vrf: RED
    shutdown: false
  Vlan4093:
    description: MLAG_PEER_L3_PEERING
    ip_address: 10.1.10.0/31
    mtu: 9000
    shutdown: false

router_bgp:
  as: 65121
  router_id: 10.1.8.1
  bgp_defaults: "{{ atd_bgp_defaults }}"
  peer_groups:
    MLAG-IPv4-UNDERLAY-PEER:
      type: ipv4
      remote_as: 65121
      next_hop_self: true
      route_map_in: RM-MLAG-PEER-IN
      send_community: all
      maximum_routes: 12000
  neighbors:
    10.1.10.1:
      peer_group: MLAG-IPv4-UNDERLAY-PEER
      description: s1-core2
  address_family_ipv4:
    peer_groups:
      MLAG-IPv4-UNDERLAY-PEER:
        activate: true
  vrfs:
    BLUE:
      rd: "10.1.8.1:502"
      router_id: 10.1.8.1
      neighbors:
        10.1.17.1:
          remote_as: 65121
          description: iBGP_VRF_BLUE_s1-core2
        10.3.1.1:
          remote_as: 65221
          description: BGP_VRF_BLUE_s2-core1
        10.3.1.3:
          remote_as: 65113
          description: BGP_VRF_BLUE_s1-brdr1
        10.3.1.4:
          remote_as: 65113
          description: BGP_VRF_BLUE_s1-brdr2
      next_hop_self: true
      redistribute_routes:
        - connected
        - static
      address_families:
        ipv4:
          neighbors:
            10.1.17.1:
              activate: true
            10.3.1.1:
              activate: true
            10.3.1.3:
              activate: true
            10.3.1.4:
              activate: true
    GREEN:
      rd: "10.1.8.1:503"
      router_id: 10.1.8.1
      neighbors:
        10.1.18.1:
          remote_as: 65121
          description: iBGP_VRF_GREEN_s1-core2
        10.3.2.1:
          remote_as: 65221
          description: BGP_VRF_GREEN_s2-core1
        10.3.2.3:
          remote_as: 65113
          description: BGP_VRF_GREEN_s1-brdr1
        10.3.2.4:
          remote_as: 65113
          description: BGP_VRF_GREEN_s1-brdr2
      next_hop_self: true
      redistribute_routes:
        - connected
        - static
      address_families:
        ipv4:
          neighbors:
            10.1.18.1:
              activate: true
            10.3.2.1:
              activate: true
            10.3.2.3:
              activate: true
            10.3.2.4:
              activate: true
    RED:
      rd: "10.1.8.1:501"
      router_id: 10.1.8.1
      neighbors:
        10.1.19.1:
          remote_as: 65121
          description: iBGP_VRF_RED_s1-core2
        10.3.3.1:
          remote_as: 65221
          description: BGP_VRF_RED_s2-core1
        10.3.3.3:
          remote_as: 65113
          description: BGP_VRF_RED_s1-brdr1
        10.3.3.4:
          remote_as: 65113
          description: BGP_VRF_RED_s1-brdr2
      next_hop_self: true
      redistribute_routes:
        - connected
        - static
      address_families:
        ipv4:
          neighbors:
            10.1.19.1:
              activate: true
            10.3.3.1:
              activate: true
            10.3.3.3:
              activate: true
            10.3.3.4:
              activate: true
custom_structured_configuration_host_ethernet_interfaces:
  Ethernet2:
    description: "s1-brdr1_Ethernet4"
    shutdown: false
    channel_group:
      id: 2
      mode: "active"
  Ethernet3:
    description: "s1-brdr2_Ethernet4"
    shutdown: false
    channel_group:
      id: 2
      mode: "active"
  Ethernet4:
    type: switched
    mode: trunk
    description: P2P_LINK_TO_s2-core1_Ethernet4
    shutdown: false
