---

- name: Setup AAA for ATD
  hosts: ATD_CVP
  connection: local
  gather_facts: no
  vars_prompt:

  #Enable to ask for username
      # - name: ansible_user
      #   prompt: What is your username?
      #   private: no

      - name: ansible_password
        prompt: What is your lab password?
        confirm: yes

  vars:
    sha512_password: "{{ ansible_password | password_hash('sha512') }}"

  tasks:
    - name: "Gather CVP facts {{inventory_hostname}}"
      import_role:
        name: 'setupAAA'

    - name: "Reset ATD lab to initial state"
      import_role:
        name: 'atd-init'
