---

- name: Initial setup of AVD devices and containers
  hosts: ATD_CVP
  connection: local
  gather_facts: no

  tasks:

    - name: "Cleaning up Tenant Container Configlet"
      command: "python3 service_scripts/configlet_remove.py"
      register: result
      ignore_errors: true

    - name: "Removing non-AVD configlets"
      tags: [apply]
      arista.cvp.cv_device_v3:
        devices: "{{CVP_DEVICES}}"
        state: present
        apply_mode: strict
      register: CVP_DEVICES

    - name: "Initial ATD Setup Complete"
      debug:
        msg: "Setup is complete execute make fabric-init next"