---

- name: Validate state of ATD Fabric
  hosts: ATD_FABRIC
  #Enable vars_prompt to ask for user:pass
  #vars_prompt:

      # - name: ansible_user
      #   prompt: What is your username?
      #   private: no

      # - name: ansible_password
      #   prompt: What is your password?

  tasks:

    - name: validate states on EOS devices
      import_role:
         name: arista.avd.eos_validate_state
