---

- name: Deploy ATD Fabric via ssh
  hosts: ATD_FABRIC

  tasks:

    - name: Deploy Configuration
      import_role:
         name: arista.avd.eos_config_deploy_eapi

  vars_prompt:

  #Enable vars_prompt to ask for user:pass

      # - name: ansible_user
      #   prompt: What is your username?
      #   private: no

      - name: ansible_password
        prompt: What is your lab password?