---

- name: Initial setup of AVD devices and containers
  hosts: ATD_CVP
  connection: local
  gather_facts: no

  tasks:

    - name: "Setup ATD lab to initial state"
      import_role:
        name: 'fabric-init'