---

- name: Configuration deployment with CVP
  hosts: ATD_CVP
  connection: local
  gather_facts: no

  vars_prompt:

      # - name: ansible_user
      #   prompt: What is your username?
      #   private: no

      - name: ansible_password
        prompt: What is your password?

  tasks:

    - name: run CVP provisioning
      import_role:
        name: arista.avd.eos_config_deploy_cvp