---

- name: Validate state of ATD Fabric
  hosts: ATD_FABRIC

  tasks:

    - name: validate states on EOS devices
      import_role:
         name: arista.avd.eos_validate_state

  vars_prompt:

      # - name: ansible_user
      #   prompt: What is your username?
      #   private: no

      - name: ansible_password
        prompt: What is your lab password?