---

- name: Build and Deploy ATD Fabric
  hosts: ATD_FABRIC

  tasks:

    - name: generate intended variables
      import_role:
         name: arista.avd.eos_designs

    - name: generate device intended config and documentation
      import_role:
         name: arista.avd.eos_cli_config_gen

- name: Configuration deployment with CVP
  hosts: ATD_CVP
  connection: local
  gather_facts: no
  #Enable vars_prompt to ask for user:pass
  #vars_prompt:

      # - name: ansible_user
      #   prompt: What is your username?
      #   private: no

      # - name: ansible_password
      #   prompt: What is your password?

  tasks:

    #  If required to include custom configlets
    #- name: upload cvp configlets
    #  import_role:
    #      name: arista.avd.cvp_configlet_upload
    #  vars:
    #    configlets_cvp_prefix: 'CUSTOM'
    #    configlet_directory: "{{inventory_dir}}/configlets"

    - name: run CVP provisioning
      import_role:
         name: arista.avd.eos_config_deploy_cvp

    - name: Remove legacy ATD configlets
      tags: removelegacy
      import_role:
         name: 'atd-remove-legacy'