---

- name: Configuration deployment with CVP
  hosts: ATD_CVP
  connection: local
  gather_facts: no

  tasks:

    - name: run CVP provisioning
      import_role:
        name: arista.avd.eos_config_deploy_cvp