---
- name: Setup AAA for ATD
  hosts: localhost

  vars_prompt:

      # - name: ansible_user
      #   prompt: What is your username?
      #   private: no

      - name: ansible_password
        prompt: What is your lab password?
        #encrypt: sha512_crypt
        confirm: yes

      - name: add_plaintxt
        prompt: Add Plaintext Password to AAA.yml?
        private: no
  vars:
    encrypted_ansible_password: "{{ ansible_password | password_hash('sha512') }}"

  tasks:

    - name: Setup AAA configs
      ansible.builtin.debug:
        msg: 'Setup AAA configs for {{ ansible_user }}'
    - name: Creating AAA config file
      file:
        path: "{{lookup('env','PWD')}}/group_vars/ATD_FABRIC/AAA.yml"
        state: touch
      #become: yes


    - name: Writing to AAA config file
      copy:
        dest: "{{lookup('env','PWD')}}/group_vars/ATD_FABRIC/AAA.yml"
        content: |
          local_users:
            arista:
              privilege: 15
              role: network-admin
              sha512_password: "{{ encrypted_ansible_password }}"

    - name: Adding plaintext password to AAA.yml file
      lineinfile:
        path: "{{lookup('env','PWD')}}/group_vars/ATD_FABRIC/AAA.yml"
        line: "ansible_password: {{ansible_password}}"
        state: present
      when: (add_plaintxt == "yes") or (add_plaintxt == "YES") or (add_plaintxt == "y") or (add_plaintxt == "Y")

# - name: Get SSH Key
#   hosts: ATD_CVP
#   connection: local
#   gather_facts: no

#   tasks:
#     - name: "Gather CVP facts {{ inventory_hostname }}"
#       arista.cvp.cv_facts:
#       register: CVP_FACTS
#     - name: "Get SSH key from {{ inventory_hostname }}"
#       template:
#         src: "{{lookup('env','PWD')}}/templates/AAA.j2"
#         dest: "{{lookup('env','PWD')}}/group_vars/ATD_FABRIC/AAA.yml"
#       vars:
#          AAA: '{{CVP_FACTS.ansible_facts.configlets | selectattr("name", "==", "ATD-INFRA") | map(attribute="config") | join(" ") | regex_findall("username .*") }}'
